apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/vasilealexandru23/ci_cd_lab@sha256:44654db0ef6b88916f5a0e215a920cdd19a94ffe1f3e8540f3a2053a1d3b73e6
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
